### ISSUE TITLE
Use of luabenchmark

### ISSUE THREAD

**Issue by vstath** [spacewander/lmdbcli#1]
Hello,

I'm trying your code and I was wondering if it's possible to include luabenchmark (your repository) to work with lmdbcli and lua script. 

If it is possible, can you share some code example? I cannot seem to load the .so library that is referenced in luabenchmark. I installed luabenchmark using luarocks, then I copied in the same directory. Is there a runtime way to configure lua lib paths?

My ultimate goal is to benchmark (from within a lua script running via lmdbcli) the performance of set/del commands as they appear quite slow at first glance.

Thank you

**Comment by spacewander** [comment]
The luabenchmark uses shared library (the `.so`) to provide its function.
However, the Lua interpreter implemented in Go doesn't support loading shared library dynamically, so it is impossible to use luabenchmark in the script.

However, you can use `pprof` or other similar tools to profile the Go host program, if you want to find out why the operation is slow.

**Comment by vstath** [comment]
Thanks a lot. Indirectly I was also asking if shared libs were in the plan to be supported (for example there's a lot of functionality that one can utilize in Lua using them (from cjson to socket functions). 

So thank you for your answers (and your code)
